checker:
  student_list: [
                  "许睿"
#    "黄国丛",
#    "袁世明",
#    "陈韬略",
#    "许方瑞",
#    "王一卓",
#    "焦凯文",
#    "陈允鑫",
#    "周洲",
#    "陶磊",
#    "罗晨尹",
#    "王运欣",
#    "刘一梵",
#    "文辰煊",
#    "陈韩",
#    "刘沁灵",
#    "张烁",
#    "高翼诚",
#    "龚轩",
#    "曾地洋",
#    "麻亮",
#    "王笳澄",
#    "张雯鑫",
#    "王悦馨",
#    "何源",
#    "程征",
#    "陈心宇",
#    "刘江",
#    "冯熙哲",
#    "李卓远",
#    "何昱君",
#    "邹元杰",
#    "张弘毅",
#    "周熙临"
  ]
  question_count: 4
  multi_file: false
  tasks_folder: "E:\\cpp-tutorial\\scripts\\AutoCpp\\tasks\\week1"

workflow:
  cmake_config: "cmake -B build -G Ninja -DCMAKE_C_COMPILER=Clang -DCMAKE_CXX_COMPILER=Clang++ -DCMAKE_CXX_STANDARD=17"
  cmake_build: "cmake --build build --config Release --clean-first -j 18"
